/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ProgramType = IDL.Variant({
  'boxCricket' : IDL.Null,
  'socialGathering' : IDL.Null,
  'exercise' : IDL.Null,
  'pickleball' : IDL.Null,
  'taskAllocation' : IDL.Null,
  'tennis' : IDL.Null,
  'badminton' : IDL.Null,
  'meetup' : IDL.Null,
});
export const ActivityLogType = IDL.Variant({
  'providerBooked' : IDL.Null,
  'sessionCreated' : IDL.Null,
  'sessionLeft' : IDL.Null,
  'sessionJoined' : IDL.Null,
  'taskCompleted' : IDL.Null,
  'taskCreated' : IDL.Null,
});
export const ActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'activityTime' : Time,
  'activityType' : ActivityLogType,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'relatedId' : IDL.Nat,
});
export const AdminStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'sessionsByType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalBookings' : IDL.Nat,
  'rejectedProviders' : IDL.Nat,
  'approvedProviders' : IDL.Nat,
  'totalProviders' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalSessions' : IDL.Nat,
  'pendingProviders' : IDL.Nat,
});
export const ProviderBooking = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'bookingTime' : Time,
  'isConfirmed' : IDL.Bool,
  'providerId' : IDL.Nat,
});
export const ProviderType = IDL.Variant({
  'sportsCompany' : IDL.Null,
  'psychologist' : IDL.Null,
});
export const ProviderApplication = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'isRejected' : IDL.Bool,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'description' : IDL.Text,
  'providerType' : ProviderType,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Principal),
  'createdAt' : Time,
  'description' : IDL.Text,
  'spaceName' : IDL.Opt(IDL.Text),
  'maxParticipants' : IDL.Nat,
  'programType' : ProgramType,
  'dateTime' : IDL.Int,
  'location' : IDL.Opt(IDL.Text),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'sessionId' : IDL.Nat,
});
export const UserProfileEntry = IDL.Record({
  'sessionsCreated' : IDL.Nat,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'sessionsJoined' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveProvider' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookProvider' : IDL.Func([IDL.Nat, Time], [IDL.Nat], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ProgramType,
        IDL.Int,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
      [IDL.Nat],
      [],
    ),
  'deleteSession' : IDL.Func([IDL.Nat], [], []),
  'getActivityLogsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(ProviderBooking)], ['query']),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderApplication)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileEntry)], ['query']),
  'getApprovedProviders' : IDL.Func(
      [],
      [IDL.Vec(ProviderApplication)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Nat], [ProviderBooking], ['query']),
  'getBookingsForProvider' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProviderBooking)],
      ['query'],
    ),
  'getBookingsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProviderBooking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySessions' : IDL.Func(
      [],
      [IDL.Vec(Session), IDL.Vec(Session)],
      ['query'],
    ),
  'getPendingProviders' : IDL.Func(
      [],
      [IDL.Vec(ProviderApplication)],
      ['query'],
    ),
  'getProvider' : IDL.Func([IDL.Nat], [ProviderApplication], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
  'getSessionsByProgramType' : IDL.Func(
      [ProgramType],
      [IDL.Vec(Session)],
      ['query'],
    ),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTasksBySession' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getTasksForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([IDL.Nat], [], []),
  'leaveSession' : IDL.Func([IDL.Nat], [], []),
  'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
  'rejectProvider' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProviderApplication' : IDL.Func(
      [ProviderType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateSession' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProgramType = IDL.Variant({
    'boxCricket' : IDL.Null,
    'socialGathering' : IDL.Null,
    'exercise' : IDL.Null,
    'pickleball' : IDL.Null,
    'taskAllocation' : IDL.Null,
    'tennis' : IDL.Null,
    'badminton' : IDL.Null,
    'meetup' : IDL.Null,
  });
  const ActivityLogType = IDL.Variant({
    'providerBooked' : IDL.Null,
    'sessionCreated' : IDL.Null,
    'sessionLeft' : IDL.Null,
    'sessionJoined' : IDL.Null,
    'taskCompleted' : IDL.Null,
    'taskCreated' : IDL.Null,
  });
  const ActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'activityTime' : Time,
    'activityType' : ActivityLogType,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'relatedId' : IDL.Nat,
  });
  const AdminStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'sessionsByType' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalBookings' : IDL.Nat,
    'rejectedProviders' : IDL.Nat,
    'approvedProviders' : IDL.Nat,
    'totalProviders' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalSessions' : IDL.Nat,
    'pendingProviders' : IDL.Nat,
  });
  const ProviderBooking = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'bookingTime' : Time,
    'isConfirmed' : IDL.Bool,
    'providerId' : IDL.Nat,
  });
  const ProviderType = IDL.Variant({
    'sportsCompany' : IDL.Null,
    'psychologist' : IDL.Null,
  });
  const ProviderApplication = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'isRejected' : IDL.Bool,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'description' : IDL.Text,
    'providerType' : ProviderType,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Principal),
    'createdAt' : Time,
    'description' : IDL.Text,
    'spaceName' : IDL.Opt(IDL.Text),
    'maxParticipants' : IDL.Nat,
    'programType' : ProgramType,
    'dateTime' : IDL.Int,
    'location' : IDL.Opt(IDL.Text),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'sessionId' : IDL.Nat,
  });
  const UserProfileEntry = IDL.Record({
    'sessionsCreated' : IDL.Nat,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'sessionsJoined' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveProvider' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookProvider' : IDL.Func([IDL.Nat, Time], [IDL.Nat], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ProgramType,
          IDL.Int,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
    'deleteSession' : IDL.Func([IDL.Nat], [], []),
    'getActivityLogsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(ProviderBooking)], ['query']),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderApplication)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileEntry)], ['query']),
    'getApprovedProviders' : IDL.Func(
        [],
        [IDL.Vec(ProviderApplication)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Nat], [ProviderBooking], ['query']),
    'getBookingsForProvider' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProviderBooking)],
        ['query'],
      ),
    'getBookingsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProviderBooking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySessions' : IDL.Func(
        [],
        [IDL.Vec(Session), IDL.Vec(Session)],
        ['query'],
      ),
    'getPendingProviders' : IDL.Func(
        [],
        [IDL.Vec(ProviderApplication)],
        ['query'],
      ),
    'getProvider' : IDL.Func([IDL.Nat], [ProviderApplication], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
    'getSessionsByProgramType' : IDL.Func(
        [ProgramType],
        [IDL.Vec(Session)],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTasksBySession' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getTasksForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([IDL.Nat], [], []),
    'leaveSession' : IDL.Func([IDL.Nat], [], []),
    'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
    'rejectProvider' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProviderApplication' : IDL.Func(
        [ProviderType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateSession' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };