/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProgramType = IDL.Variant({
  'boxCricket' : IDL.Null,
  'socialGathering' : IDL.Null,
  'exercise' : IDL.Null,
  'pickleball' : IDL.Null,
  'taskAllocation' : IDL.Null,
  'tennis' : IDL.Null,
  'badminton' : IDL.Null,
  'meetup' : IDL.Null,
});
export const Time = IDL.Int;
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Principal),
  'createdAt' : Time,
  'description' : IDL.Text,
  'maxParticipants' : IDL.Nat,
  'programType' : ProgramType,
  'dateTime' : IDL.Int,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'sessionId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSession' : IDL.Func(
      [IDL.Text, IDL.Text, ProgramType, IDL.Int, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
      [IDL.Nat],
      [],
    ),
  'deleteSession' : IDL.Func([IDL.Nat], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySessions' : IDL.Func(
      [],
      [IDL.Vec(Session), IDL.Vec(Session)],
      ['query'],
    ),
  'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
  'getSessionsByProgramType' : IDL.Func(
      [ProgramType],
      [IDL.Vec(Session)],
      ['query'],
    ),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTasksBySession' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([IDL.Nat], [], []),
  'leaveSession' : IDL.Func([IDL.Nat], [], []),
  'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProgramType = IDL.Variant({
    'boxCricket' : IDL.Null,
    'socialGathering' : IDL.Null,
    'exercise' : IDL.Null,
    'pickleball' : IDL.Null,
    'taskAllocation' : IDL.Null,
    'tennis' : IDL.Null,
    'badminton' : IDL.Null,
    'meetup' : IDL.Null,
  });
  const Time = IDL.Int;
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Principal),
    'createdAt' : Time,
    'description' : IDL.Text,
    'maxParticipants' : IDL.Nat,
    'programType' : ProgramType,
    'dateTime' : IDL.Int,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'sessionId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSession' : IDL.Func(
        [IDL.Text, IDL.Text, ProgramType, IDL.Int, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
    'deleteSession' : IDL.Func([IDL.Nat], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySessions' : IDL.Func(
        [],
        [IDL.Vec(Session), IDL.Vec(Session)],
        ['query'],
      ),
    'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
    'getSessionsByProgramType' : IDL.Func(
        [ProgramType],
        [IDL.Vec(Session)],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTasksBySession' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([IDL.Nat], [], []),
    'leaveSession' : IDL.Func([IDL.Nat], [], []),
    'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };