/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ProgramType = { 'boxCricket' : null } |
  { 'socialGathering' : null } |
  { 'exercise' : null } |
  { 'pickleball' : null } |
  { 'taskAllocation' : null } |
  { 'tennis' : null } |
  { 'badminton' : null } |
  { 'meetup' : null };
export interface Session {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'participants' : Array<Principal>,
  'createdAt' : Time,
  'description' : string,
  'maxParticipants' : bigint,
  'programType' : ProgramType,
  'dateTime' : bigint,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'assignedTo' : [] | [Principal],
  'createdAt' : Time,
  'completed' : boolean,
  'description' : string,
  'sessionId' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSession' : ActorMethod<
    [string, string, ProgramType, bigint, bigint],
    bigint
  >,
  'createTask' : ActorMethod<
    [bigint, string, string, [] | [Principal]],
    bigint
  >,
  'deleteSession' : ActorMethod<[bigint], undefined>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMySessions' : ActorMethod<[], [Array<Session>, Array<Session>]>,
  'getSession' : ActorMethod<[bigint], Session>,
  'getSessionsByProgramType' : ActorMethod<[ProgramType], Array<Session>>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTasksBySession' : ActorMethod<[bigint], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSession' : ActorMethod<[bigint], undefined>,
  'leaveSession' : ActorMethod<[bigint], undefined>,
  'markTaskComplete' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];